slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: JACOBI #SCHUR_JACOBI
    ceres_trust_strategy: DOGLEG #LEVENBERG_MARQUARDT
    ceres_dogleg_type: SUBSPACE_DOGLEG #TRADITIONAL_DOGLEG
    ceres_loss_function: HuberLoss #None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping #localization
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.01 #0.02 #if 0 never publishes odometry
    map_update_interval: 3.0 #5.0
    resolution: 0.05
    max_laser_range: 10.0 #for rastering images
    minimum_time_interval: 0.1 #0.5
    transform_timeout: 0.2
    tf_buffer_duration: 10.0
    stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps
    enable_interactive_mode: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2 #0.5
    scan_buffer_size: 20 #10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.05 #0.1  
    link_scan_maximum_distance: 3.0 #1.5
    loop_search_maximum_distance: 5.0 #3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 1 #10           
    loop_match_maximum_variance_coarse: 10.0 #3.0  
    loop_match_minimum_response_coarse: 0.1 #0.15 #0.35    
    loop_match_minimum_response_fine: 0.2 #0.25 #0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 1.0 #0.5
    correlation_search_space_resolution: 0.03 #0.01
    correlation_search_space_smear_deviation: 0.12 #0.1

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 10.0 #8.0
    loop_search_space_resolution: 0.2 #0.09 #0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 0.5 #1.0    

    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.6 #0.349   
    coarse_angle_resolution: 0.06 #0.0349        
    minimum_angle_penalty: 0.1 #0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
